(source gnu)
(source melpa)

(depends-on "bind-key")
(depends-on "cask")
(depends-on "dash")
(depends-on "drag-stuff")
(depends-on "exec-path-from-shell")
(depends-on "expand-region")
(depends-on "f")
(depends-on "flycheck")
(depends-on "flycheck-cask")
(depends-on "htmlize")
(depends-on "idle-highlight-mode")
(depends-on "magit")
(depends-on "multiple-cursors")
(depends-on "nyan-mode")
(depends-on "pallet")
(depends-on "popwin")
(depends-on "prodigy")
(depends-on "projectile")
(depends-on "s")
(depends-on "smartparens")
(depends-on "smex")
(depends-on "use-package")
(depends-on "web-mode")
(depends-on "yasnippet")
(depends-on "paredit")
(depends-on "rust-mode")
(depends-on "yaml-mode")
;; Make ido great again!
(depends-on "ido-ubiquitous")
;; Friendship is magic!
(depends-on "rainbow-delimiters")
;; If ever EVER I need to edit HTML this helps.
(depends-on "tagedit")
;; I do write Python yet.
(depends-on "elpy")
(depends-on "python-mode")
;; Docker docker docker file!
(depends-on "dockerfile-mode")
(depends-on "vagrant")
;; I even write Ruby!
(depends-on "enh-ruby-mode")
;; Yes I do write Go and kinda like it :)
(depends-on "go-mode")
(depends-on "go-autocomplete")
(depends-on "go-guru")
(depends-on "flymake-go")
(depends-on "auto-complete")
;; Show me the bounds!
(depends-on "fill-column-indicator")
;; C/C++ stuff
(depends-on "rtags")
(depends-on "helm")
(depends-on "auto-complete-clang-async")
(depends-on "groovy-mode")
(depends-on "gruvbox-theme")
